// 轻流门户管理页提交数据格式
export const config = {
  authMembers: null,
  beingFavorite: false,
  componentStatus: {
    carouselStatus: true,
    favouriteStatus: true,
    gridStatus: true,
    linkStatus: true,
    memberHavingWsStatus: true,
    taskStatus: true,
  },
  components: [
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: null,
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 6,
          x: 0,
          y: 118,
          dashTempId: -13,
        },
        pc: {
          cols: 12,
          rows: 6,
          x: 0,
          y: 0,
          dashTempId: -13,
        },
      },
      taskConfig: null,
      textConfig: {
        text: '',
      },
      type: 5,
      dashTempId: -13,
      id: '-13',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: null,
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 6,
          x: 0,
          y: 112,
          dashTempId: -14,
        },
        pc: {
          cols: 12,
          rows: 6,
          x: 12,
          y: 0,
          dashTempId: -14,
        },
      },
      taskConfig: null,
      textConfig: {
        text: '',
      },
      type: 5,
      dashTempId: -14,
      id: '-14',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: {
        beingShowTitle: true,
        gridId: 39739,
        gridTitle: '宫格',
        items: [],
        position: {
          mobile: {
            cols: 6,
            rows: 5,
            x: 0,
            y: 91,
          },
          pc: {
            cols: 10,
            rows: 7,
            x: 0,
            y: 6,
          },
        },
        frontDisplayInfo: {
          showMore: false,
        },
      },
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 5,
          x: 0,
          y: 91,
          dashTempId: -2,
        },
        pc: {
          cols: 10,
          rows: 7,
          x: 0,
          y: 6,
          dashTempId: -2,
        },
      },
      taskConfig: null,
      textConfig: null,
      type: 2,
      dashTempId: -2,
      id: '-2',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: null,
      linkConfig: {
        beingLoginAuth: false,
        url: 'https://news.baidu.com',
      },
      position: {
        mobile: {
          cols: 6,
          rows: 6,
          x: 0,
          y: 100,
          dashTempId: -10,
        },
        pc: {
          cols: 12,
          rows: 6,
          x: 11,
          y: 6,
          dashTempId: -10,
        },
      },
      taskConfig: null,
      textConfig: null,
      type: 4,
      dashTempId: -10,
      id: '-10',
      isLoading: true,
    },
    {
      carouselConfig: {
        carouselId: 20684,
        filterConfig: [],
        imageQue: null,
        jumpMode: 1,
        linkQue: null,
        showLatestLimit: 3,
        sourceApp: {
          appKey: null,
          formTitle: null,
        },
        titleQue: null,
        carouselData: {
          jumpMode: 1,
          slides: [],
        },
      },
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: null,
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 3,
          x: 0,
          y: 94,
          dashTempId: -7,
        },
        pc: {
          cols: 12,
          rows: 6,
          x: 0,
          y: 13,
          dashTempId: -7,
        },
      },
      taskConfig: null,
      textConfig: null,
      type: 3,
      dashTempId: -7,
      id: '-7',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: {
        beingShowTitle: true,
        beingUsing: true,
        favouriteId: null,
        favouriteTitle: '常用',
        items: [],
        position: {
          mobile: {
            cols: 6,
            rows: 5,
            x: 0,
            y: 86,
          },
          pc: {
            cols: 10,
            rows: 8,
            x: 0,
            y: 19,
          },
        },
      },
      filterConfig: null,
      gridConfig: null,
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 5,
          x: 0,
          y: 86,
          dashTempId: -17,
        },
        pc: {
          cols: 10,
          rows: 8,
          x: 0,
          y: 19,
          dashTempId: -17,
        },
      },
      taskConfig: null,
      textConfig: null,
      type: 7,
      dashTempId: -17,
      id: '-17',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: null,
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 4,
          x: 0,
          y: 81,
          dashTempId: -18,
        },
        pc: {
          cols: 12,
          rows: 4,
          x: 0,
          y: 27,
          dashTempId: -18,
        },
      },
      taskConfig: {
        beingShowHint: true,
        beingShowTitle: true,
        beingUsing: true,
        componentTaskHint: '及时处理待办，可以有效提升流程效率',
        componentTaskId: 4762,
        componentTaskTitle: '待办',
        dashTaskConfigList: [
          {
            beingCheck: true,
            createTime: null,
            dashId: 1019042,
            dashTaskId: 4762,
            id: 14140,
            ordinal: 0,
            title: 'all.taskTodo',
            type: 1,
            updateTime: null,
            num: 2,
            hoverTitle: 'all.taskProcessNow',
          },
          {
            beingCheck: true,
            createTime: null,
            dashId: 1019042,
            dashTaskId: 4762,
            id: 14141,
            ordinal: 1,
            title: 'all.taskTimeout',
            type: 2,
            updateTime: null,
            num: 0,
            hoverTitle: 'all.taskProcessNow',
          },
          {
            beingCheck: true,
            createTime: null,
            dashId: 1019042,
            dashTaskId: 4762,
            id: 14142,
            ordinal: 2,
            title: 'all.taskUpcomingTimeout',
            type: 3,
            updateTime: null,
            num: 0,
            hoverTitle: 'all.taskProcessNow',
          },
          {
            beingCheck: true,
            createTime: null,
            dashId: 1019042,
            dashTaskId: 4762,
            id: 14143,
            ordinal: 3,
            title: 'all.taskRemind',
            type: 4,
            updateTime: null,
            num: 0,
            hoverTitle: 'all.taskProcessNow',
          },
          {
            beingCheck: false,
            createTime: null,
            dashId: 1019042,
            dashTaskId: 4762,
            id: 14144,
            ordinal: 4,
            title: 'all.taskToBeImproved',
            type: 9,
            updateTime: null,
          },
          {
            beingCheck: false,
            createTime: null,
            dashId: 1019042,
            dashTaskId: 4762,
            id: 14145,
            ordinal: 5,
            title: 'all.taskCopyingItem',
            type: 6,
            updateTime: null,
          },
          {
            beingCheck: false,
            createTime: null,
            dashId: 1019042,
            dashTaskId: 4762,
            id: 14146,
            ordinal: 6,
            title: 'all.taskDrafts',
            type: 7,
            updateTime: null,
          },
          {
            beingCheck: false,
            createTime: null,
            dashId: 1019042,
            dashTaskId: 4762,
            id: 14147,
            ordinal: 7,
            title: 'all.taskApplications',
            type: 5,
            updateTime: null,
          },
          {
            beingCheck: false,
            createTime: null,
            dashId: 1019042,
            dashTaskId: 4762,
            id: 14148,
            ordinal: 8,
            title: 'all.taskDone',
            type: 8,
            updateTime: null,
          },
        ],
        position: null,
      },
      textConfig: null,
      type: 8,
      dashTempId: -18,
      id: '-18',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: {
        beingShowTitle: true,
        gridId: 39740,
        gridTitle: '宫格',
        items: [
          {
            beingCustomTitle: true,
            beingShowTitle: null,
            customTitle: '百度',
            gridId: 39740,
            iconUrl: 'https://file.qingflow.com/assets/mobile/images/link_1.png',
            id: 62875,
            jumpMode: 2,
            linkAppKey: null,
            linkDashKey: null,
            linkFormType: null,
            linkTagId: null,
            linkUrl: 'https://baidu.com',
            ordinal: 0,
            title: '百度',
            type: 4,
          },
          {
            beingCustomTitle: true,
            beingShowTitle: null,
            customTitle: 'example',
            gridId: 39740,
            iconUrl: 'https://file.qingflow.com/assets/mobile/images/link_1.png',
            id: 62876,
            jumpMode: 1,
            linkAppKey: null,
            linkDashKey: null,
            linkFormType: null,
            linkTagId: null,
            linkUrl: 'https://example.com',
            ordinal: 1,
            title: 'example',
            type: 4,
          },
        ],
        position: {
          mobile: {
            cols: 6,
            rows: 5,
            x: 0,
            y: 11,
          },
          pc: {
            cols: 10,
            rows: 6,
            x: 0,
            y: 31,
          },
        },
        frontDisplayInfo: {
          showMore: false,
        },
      },
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 5,
          x: 0,
          y: 11,
          dashTempId: -3,
        },
        pc: {
          cols: 10,
          rows: 6,
          x: 0,
          y: 31,
          dashTempId: -3,
        },
      },
      taskConfig: null,
      textConfig: null,
      type: 2,
      dashTempId: -3,
      id: '-3',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: null,
      linkConfig: {
        beingLoginAuth: false,
        url: 'https://news.baidu.com/',
      },
      position: {
        mobile: {
          cols: 6,
          rows: 6,
          x: 0,
          y: 19,
          dashTempId: -11,
        },
        pc: {
          cols: 12,
          rows: 6,
          x: 10,
          y: 31,
          dashTempId: -11,
        },
      },
      taskConfig: null,
      textConfig: null,
      type: 4,
      dashTempId: -11,
      id: '-11',
      isLoading: true,
    },
    {
      carouselConfig: {
        carouselId: 20685,
        filterConfig: [],
        imageQue: null,
        jumpMode: 1,
        linkQue: null,
        showLatestLimit: 3,
        sourceApp: {
          appKey: null,
          formTitle: null,
        },
        titleQue: null,
        carouselData: {
          jumpMode: 1,
          slides: [],
        },
      },
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: null,
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 3,
          x: 0,
          y: 16,
          dashTempId: -8,
        },
        pc: {
          cols: 12,
          rows: 6,
          x: 0,
          y: 37,
          dashTempId: -8,
        },
      },
      taskConfig: null,
      textConfig: null,
      type: 3,
      dashTempId: -8,
      id: '-8',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: {
        beingShowTitle: true,
        gridId: 39741,
        gridTitle: '宫格',
        items: [
          {
            beingCustomTitle: false,
            beingShowTitle: null,
            customTitle: '未命名的门户',
            gridId: 39741,
            iconUrl:
              '{"icon":"https://file.qingflow.com/assets/mobile/images/dashboard_money.png","iconColor":"qing-orange"}',
            id: 63939,
            jumpMode: 1,
            linkAppKey: null,
            linkDashKey: '23b6ee07',
            linkFormType: null,
            linkTagId: null,
            linkUrl: null,
            ordinal: 0,
            title: '政务管理门户',
            type: 2,
          },
          {
            beingCustomTitle: false,
            beingShowTitle: null,
            customTitle: '员工请假审批',
            gridId: 39741,
            iconUrl: 'https://file.qingflow.com/assets/mobile/images/icon_application_Code.png',
            id: 63940,
            jumpMode: 1,
            linkAppKey: '28cabf26',
            linkDashKey: null,
            linkFormType: 1,
            linkTagId: null,
            linkUrl: null,
            ordinal: 1,
            title: '员工请假审批',
            type: 1,
          },
          {
            beingCustomTitle: false,
            beingShowTitle: null,
            customTitle: '员工信息表',
            gridId: 39741,
            iconUrl: 'https://file.qingflow.com/assets/mobile/images/icon_application_add.png',
            id: 63941,
            jumpMode: 1,
            linkAppKey: '4cb5f12c',
            linkDashKey: null,
            linkFormType: 1,
            linkTagId: null,
            linkUrl: null,
            ordinal: 2,
            title: '员工信息表',
            type: 1,
          },
          {
            beingCustomTitle: false,
            beingShowTitle: null,
            customTitle: '未命名应用包',
            gridId: 39741,
            iconUrl:
              '{"icon":"https://file.qingflow.com/assets/mobile/images/pkg_1.png","iconColor":"qing-orange"}',
            id: 63942,
            jumpMode: 1,
            linkAppKey: null,
            linkDashKey: null,
            linkFormType: null,
            linkTagId: 1261188,
            linkUrl: null,
            ordinal: 3,
            title: '政务相关-应用包',
            type: 3,
          },
          {
            beingCustomTitle: false,
            beingShowTitle: null,
            customTitle: '关联已有数据',
            gridId: 39741,
            iconUrl: 'https://file.qingflow.com/assets/mobile/images/pkg_5.png',
            id: 63943,
            jumpMode: 1,
            linkAppKey: null,
            linkDashKey: null,
            linkFormType: null,
            linkTagId: 1261098,
            linkUrl: null,
            ordinal: 4,
            title: '关联已有数据',
            type: 3,
          },
        ],
        position: {
          mobile: {
            cols: 6,
            rows: 5,
            x: 0,
            y: 31,
          },
          pc: {
            cols: 11,
            rows: 4,
            x: 12,
            y: 37,
          },
        },
        frontDisplayInfo: {
          showMore: true,
        },
      },
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 5,
          x: 0,
          y: 31,
          dashTempId: -4,
        },
        pc: {
          cols: 11,
          rows: 4,
          x: 12,
          y: 37,
          dashTempId: -4,
        },
      },
      taskConfig: null,
      textConfig: null,
      type: 2,
      dashTempId: -4,
      id: '-4',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: null,
      linkConfig: {
        beingLoginAuth: false,
        url: 'https://qingflow.com/f/1c7ade79',
      },
      position: {
        mobile: {
          cols: 6,
          rows: 6,
          x: 0,
          y: 36,
          dashTempId: -12,
        },
        pc: {
          cols: 12,
          rows: 6,
          x: 12,
          y: 41,
          dashTempId: -12,
        },
      },
      taskConfig: null,
      textConfig: null,
      type: 4,
      dashTempId: -12,
      id: '-12',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: null,
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 6,
          x: 0,
          y: 25,
          dashTempId: -15,
        },
        pc: {
          cols: 12,
          rows: 6,
          x: 0,
          y: 43,
          dashTempId: -15,
        },
      },
      taskConfig: null,
      textConfig: {
        text: '<p>这是一段文本，哈哈。</p><p><strong>感谢！</strong></p><ol><li>test</li><li>testtt</li></ol><p><img src="https://file.qingflow.com/uploads/file/cff56ecd-48fe-4551-a677-b5a1553f790c.png"></p><p>阿斯蒂芬</p>',
      },
      type: 5,
      dashTempId: -15,
      id: '-15',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: {
        beingShowTitle: true,
        gridId: 39742,
        gridTitle: '宫格',
        items: [
          {
            beingCustomTitle: false,
            beingShowTitle: null,
            customTitle: '未命名的门户',
            gridId: 39742,
            iconUrl:
              '{"icon":"https://file.qingflow.com/assets/mobile/images/dashboard_money.png","iconColor":"qing-orange"}',
            id: 64090,
            jumpMode: 1,
            linkAppKey: null,
            linkDashKey: '23b6ee07',
            linkFormType: null,
            linkTagId: null,
            linkUrl: null,
            ordinal: 0,
            title: '政务管理门户',
            type: 2,
          },
        ],
        position: {
          mobile: {
            cols: 6,
            rows: 5,
            x: 0,
            y: 47,
          },
          pc: {
            cols: 10,
            rows: 7,
            x: 0,
            y: 49,
          },
        },
        frontDisplayInfo: {
          showMore: false,
        },
      },
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 5,
          x: 0,
          y: 47,
          dashTempId: -5,
        },
        pc: {
          cols: 10,
          rows: 7,
          x: 0,
          y: 49,
          dashTempId: -5,
        },
      },
      taskConfig: null,
      textConfig: null,
      type: 2,
      dashTempId: -5,
      id: '-5',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: {
        beingShowTitle: true,
        gridId: 39743,
        gridTitle: '宫格',
        items: [],
        position: {
          mobile: {
            cols: 6,
            rows: 5,
            x: 0,
            y: 42,
          },
          pc: {
            cols: 10,
            rows: 7,
            x: 10,
            y: 49,
          },
        },
        frontDisplayInfo: {
          showMore: false,
        },
      },
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 5,
          x: 0,
          y: 42,
          dashTempId: -6,
        },
        pc: {
          cols: 10,
          rows: 7,
          x: 10,
          y: 49,
          dashTempId: -6,
        },
      },
      taskConfig: null,
      textConfig: null,
      type: 2,
      dashTempId: -6,
      id: '-6',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: {
        appKey: '582405fc',
        biChartId: null,
        chartKey: '3664b20d',
        chartName: '申请人年龄统计',
        chartType: 1,
        dataSourceType: null,
        pageLoading: false,
      },
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: null,
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 3,
          x: 0,
          y: 76,
          dashTempId: -1,
        },
        pc: {
          cols: 12,
          rows: 6,
          x: 0,
          y: 56,
          dashTempId: -1,
        },
      },
      taskConfig: null,
      textConfig: null,
      type: 1,
      dashTempId: -1,
      id: '-1',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: {
        createTime: null,
        dashId: 1019042,
        filterConfig: [
          {
            filterGroupConfig: [
              {
                dftJudgeType: 6,
                dftJudgeValue: [
                  {
                    dataValue: null,
                    email: null,
                    id: null,
                    optionId: null,
                    ordinal: null,
                    otherInfo: null,
                    pluginValue: null,
                    queId: null,
                    value: '25',
                  },
                ],
                filterCondition: [
                  {
                    biFieldId: null,
                    chartKey: '3664b20d',
                    chartName: '申请人年龄统计',
                    queId: 51619228,
                    queOriginType: null,
                    queTitle: '年龄',
                    queType: 8,
                  },
                ],
                filterItemId: 274372,
                filterItemName: '年龄筛选',
                judgeType: 6,
                judgeAnswer: [
                  {
                    dataValue: null,
                    email: null,
                    id: null,
                    optionId: null,
                    ordinal: null,
                    otherInfo: null,
                    pluginValue: null,
                    queId: null,
                    value: '25',
                  },
                ],
              },
            ],
            filterGroupId: 165143,
            filterGroupName: '筛选组',
          },
        ],
        id: 127434,
        lastUpdateTime: null,
      },
      gridConfig: null,
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 1,
          x: 0,
          y: 77,
          dashTempId: -19,
        },
        pc: {
          cols: 12,
          rows: 3,
          x: 12,
          y: 56,
          dashTempId: -19,
        },
      },
      taskConfig: null,
      textConfig: null,
      type: 6,
      dashTempId: -19,
      id: '-19',
      isLoading: true,
    },
    {
      carouselConfig: {
        carouselId: 20686,
        filterConfig: [],
        imageQue: null,
        jumpMode: 1,
        linkQue: null,
        showLatestLimit: 3,
        sourceApp: {
          appKey: null,
          formTitle: null,
        },
        titleQue: null,
        carouselData: {
          jumpMode: 1,
          slides: [],
        },
      },
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: null,
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 6,
          x: 0,
          y: 52,
          dashTempId: -9,
        },
        pc: {
          cols: 10,
          rows: 8,
          x: 0,
          y: 62,
          dashTempId: -9,
        },
      },
      taskConfig: null,
      textConfig: null,
      type: 3,
      dashTempId: -9,
      id: '-9',
      isLoading: true,
    },
    {
      carouselConfig: null,
      chartConfig: null,
      favouriteConfig: null,
      filterConfig: null,
      gridConfig: null,
      linkConfig: null,
      position: {
        mobile: {
          cols: 6,
          rows: 6,
          x: 0,
          y: 58,
          dashTempId: -16,
        },
        pc: {
          cols: 12,
          rows: 6,
          x: 11,
          y: 62,
          dashTempId: -16,
        },
      },
      taskConfig: null,
      textConfig: {
        text: '',
      },
      type: 5,
      dashTempId: -16,
      id: '-16',
      isLoading: true,
    },
  ],
  dashAuth: 3,
  dashIcon:
    '{"icon":"https://file.qingflow.com/assets/mobile/images/dashboard_money.png","iconColor":"qing-orange"}',
  dashKey: '23b6ee07',
  dashName: '政务管理门户',
  deleteItemStatus: true,
  editItemStatus: true,
  favouriteTagId: null,
  hideCopyright: false,
  publishStatus: 2,
  tagIds: [1261188],
  tags: [
    {
      addAppStatus: null,
      ordinal: null,
      tagIcon:
        '{"icon":"https://file.qingflow.com/assets/mobile/images/pkg_1.png","iconColor":"qing-orange"}',
      tagId: 1261188,
      tagName: '政务相关-应用包',
    },
  ],
  wsType: null,
};
